version: '3.4'
networks:
 dockerapi-dev:
  driver: bridge

services:
  collnextguess.api:
    image: ${DOCKER_REGISTRY-}collnextguessapi
    depends_on:
    - "postgres_image"
    build:
      context: .
      dockerfile: CollNextGuess.Api/Dockerfile
    ports:
    - "8000:80"
    environment:
     DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=VBoxBkdTest;username=app_user;password=1!@Pal4t0&96"
    networks:
    - dockerapi-dev

  postgres_image:
   image: postgres:latest
   ports:
   - "5432"
   restart: always
   volumes:
   - db_volume:/var/lib/postgressql/data
   environment:
    POSTGRES_USER: "app_user"
    POSTGRES_PASSWORD: "appuserpass"
    POSTGRES_DB: "VBoxBkdTest"

volumes:
 db_volume: